#!/usr/bin/python
from cmd import Cmd
from My_Style import Color,Style,Animation,is_exist
import os ,sys ,subprocess

from tools import (
        Tools_shell,
        Style_shell,
        )

# Database...
from tools.DATA import (
HELP_MAIN as HELP, # text...
ABOUT_MAIN as ABOUT, # text...
PROMPT,
SHELL_ALL,
)

# The Theme of the tool
Color.Theme('light')

class shell(SHELL_ALL):
    # the shell command...
    prompt = PROMPT('No Name')

    def help(self):
        return self.SQUARE(HELP)

    def do_update(self,arg):
        if is_exist('sudo'): # check if root exist
            DEL = 'sudo rm -rif '
        else:
            DEL = 'rm -rif '

        PATH = os.getcwd() # Tool path
        subprocess.run(DEL+PATH) # delete old version

        # download new version...
        os.chdir(PATH.replace('N404-Tool',''))
        subprocess.run('git clone https://github.com/No-Name-404/N404-Tool')
        exit(Color.reader('G#Done: W#run the tool agin...\n'))

    def do_about(self,arg):
        # display the About text...
        Animation.SlowLine(SQUARE(ABOUT),t=0.02)

    def do_Tools(self,arg):
        # start the Tools section...
        Tools_shell.shell_main = super(shell,self).cmdloop
        Tools_shell().cmdloop(Tools_shell().help())

    def do_Style(self,arg):
        # start the Style section...
        Style_shell.shell_main = super(shell,self).cmdloop
        Style_shell().cmdloop(Style_shell().help())

    def do_Hash(self,arg):
        print ('It will be available soon...')

    def do_Fishing(self,arg):
        print ('It will be available soon...')

    def do_Telebot(self,arg):
        print ('It will be available soon...')

if __name__=='__main__': # Check if run as main
    shell().cmdloop() # start the N404-Tool
