#!/usr/bin/python3 -B
import os, sys
from N4Tools.System import is_in_bin

if is_in_bin('sudo'):
    root = 'sudo '
else:
    root = ''
path = os.environ['SHELL'].replace('bin/bash','lib/N404-Tool/start')
try:
    if len(sys.argv) > 1:
       os.system(f'{root}python3 -B {path} '+sys.argv[1])
    else:
       os.system(f'{root}python3 -B {path}')
except KeyboardInterrupt:
    exit()
