#!/usr/bin/python3 -B
from cmd import Cmd
from N4Tools.Design import Color,Style,Animation
import os ,sys ,subprocess

from tools import (
        Tools_shell,Style_shell,
        Hash_shell,Telebot_shell,
        Password_shell)

from tools.root import (
HELP_MAIN as HELP, # text...
ABOUT_MAIN as ABOUT, # text...
HELP_TOOL,NEW_TOOL,
SHELL_ALL,EasyCmd,
TOOLS_PATH,XPATH )

from tools.root.db import RULER
Color.Theme('light')

if 'com.termux' in os.getcwd():
    DEL = 'rm -rif '
else:
    DEL = 'sudo rm -rif '

# The code is very frequent,
# this is the appropriate solution.
temp = '''
    def do_{name}(self,arg):
        os.system('clear')
        {name}_shell.shell_main = super(shell, self).cmdloop
        {name}_shell().cmdloop({name}_shell().help())
    '''
sections = 'class Sections:'
for i in ['Tools','Style','Hash','Telebot','Password']:
    sections += temp.format(name=i)
exec(sections)
# end...

class shell(SHELL_ALL,Sections):
    # the shell command...
    page = 'main'

    def __init__(self):
        super().__init__()

    def help(self):
        return self.SQUARE(HELP)

    def do_update(self,arg):
        # download new version...
        subprocess.run(DEL+'N404-Tool',shell=True)
        subprocess.run('git clone https://github.com/No-Name-404/N404-Tool',shell=True)
        os.chdir('N404-Tool/')
        subprocess.run('python3 -B setup.py',shell=True)
        print(Color.reader('\033[0;37m[ G#OK\033[0;37m ] N404-Tool has been downloaded...'))
        print(Color.reader('\033[0;37m[ G#OK\033[0;37m ] N404-Tool has been setup...'))
        exit(Color.reader('G#Done: W#run the tool agin...\033[0;37m'))

    def do_delete(self,arg):
        # delete the tool from the system...
        user = input(Color.reader('R#Do you really want to delete the tool?\n  [G#yR#/n] :\033[0;37m '))
        if user.lower().strip() == 'y':
            subprocess.run(DEL+os.environ['SHELL'].replace('bash', 'N404-Tool'),shell=True)
            subprocess.run(DEL+os.environ['SHELL'].replace('bin/bash', 'lib/N404-Tool'),shell=True)
            subprocess.run(DEL+(os.getcwd() if os.getcwd().endswith('-Tool') else os.getcwd()+'/N404-Tool' ),shell=True)
            user = input(Color.reader('R#Do you want to delete the database?\n  [G#yR#/n] :\033[0;37m '))
            if user.lower().strip() == 'y':
                subprocess.run(DEL+os.environ['SHELL'].replace('bin/bash', 'lib/db.json'),shell=True)
            exit()

    def do_about(self,arg):
        # display the About text...
        self.SQUARE(self.SQUARE(ABOUT),type=False)

if __name__=='__main__': # Check if run as main
    if len(sys.argv) > 1:
        text = sys.argv[1].lower()
        if text == 'hash':
            shell().do_Hash(shell().cmdloop)
        elif text == 'style':
            shell().do_Style(shell().cmdloop)
        elif text == 'tools':
            shell().do_Tools(shell().cmdloop)
        elif text == 'telebot':
            shell().do_Telebot(shell().cmdloop)
        elif text == 'password':
            shell().do_Password(shell().cmdloop)

        elif text == 'easycmd':
            EasyCmd = EasyCmd()
            EasyCmd.write()
        elif text == 'update':
            shell().do_update(None)
        elif text == 'new':
            print (NEW_TOOL)

        else:
            print (HELP_TOOL)
    else:
        os.system('clear')
        shell().cmdloop() # start the N404-Tool
